config/routes.rb
OusamakingWeb::Application.routes.draw do

  resources :groups
  resources :friends

  devise_for :users
  get 'friends', :to => 'groups#index', :as => :user_root 
  get "home/index"

  root :to => "groups#index"
  
  match 'groups/current_status/:id' => 'groups#current_status', :as => :current_status_group

end

app/models/friend.rb
class Friend < ActiveRecord::Base
  belongs_to :group
  validates_presence_of :group_id, :name, :email
end

app/models/group.rb
class Group < ActiveRecord::Base
    has_many :friends, :dependent=>:destroy
    validates_presence_of :name
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable, :lockable and :timeoutable
  devise :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/friends_controller.rb
class FriendsController < ApplicationController
  before_filter :authenticate_user!  
  # GET /friends
  # GET /friends.xml
  def index
    @friends = Friend.all(:conditions=>{:created_by=>current_user.id})

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @friends }
    end
  end

  # GET /friends/1
  # GET /friends/1.xml
  def show
    @friend = Friend.find(params[:id],:conditions=>{:created_by=>current_user.id})

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @friend }
    end
  end

  # GET /friends/new
  # GET /friends/new.xml
  def new
    @friend = Friend.new
		@friend.group_id = params[:friend][:group_id].to_i if params[:friend] && params[:friend][:group_id]
		
    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @friend }
    end
  end

  # GET /friends/1/edit
  def edit
    @friend = Friend.find(params[:id],:conditions=>{:created_by=>current_user.id})
  end

  # POST /friends
  # POST /friends.xml
  def create
    @friend = Friend.new(params[:friend])
    @friend.created_by = current_user.id

    respond_to do |format|
      if @friend.save
        format.html { redirect_to(groups_path, :notice => "Group #{@friend.group.name} was updated.") }
        format.xml  { render :xml => @friend, :status => :created, :location => @friend }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @friend.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /friends/1
  # PUT /friends/1.xml
  def update
    @friend = Friend.find(params[:id],:conditions=>{:created_by=>current_user.id})

    respond_to do |format|
      if @friend.update_attributes(params[:friend])
        format.html { redirect_to(groups_path, :notice => "Group #{@friend.group.name} was updated.") }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @friend.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /friends/1
  # DELETE /friends/1.xml
  def destroy
    @friend = Friend.find(params[:id],:conditions=>{:created_by=>current_user.id})
    @friend.destroy

    respond_to do |format|
      format.html { redirect_to(groups_path, :notice => "Group #{@friend.group.name} was updated.") }
      format.xml  { head :ok }
    end
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_filter :authenticate_user!
  # GET /groups
  # GET /groups.xml
  def index
    @groups = Group.all(:order=>"id desc",:limit=>5,:conditions=>{:created_by=>current_user.id})

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @groups }
    end
  end

  # GET /groups/1
  # GET /groups/1.xml
  def show
    @group = Group.find(params[:id],:conditions=>{:created_by=>current_user.id})

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @group }
    end
  end

  # GET /groups/new
  # GET /groups/new.xml
  def new
    @group = Group.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @group }
    end
  end

  # GET /groups/1/edit
  def edit
    @group = Group.find(params[:id], :conditions=>{:created_by=>current_user.id})
  end

  # POST /groups
  # POST /groups.xml
  def create
    @group = Group.new(params[:group])
    @group.created_by = current_user.id

    respond_to do |format|
      if @group.save
        #format.html { redirect_to(@group, :notice => 'Group was successfully created.') }
        format.html { redirect_to(groups_path, :notice => "Group #{@group.name} was successfully updated.") }
        format.xml  { render :xml => @group, :status => :created, :location => @group }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @group.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /groups/1
  # PUT /groups/1.xml
  def update
    @group = Group.find(params[:id],:conditions=>{:created_by=>current_user.id})

    respond_to do |format|
      if @group.update_attributes(params[:group])
        #format.html { redirect_to(@group, :notice => 'Group was successfully updated.') }
        format.html { redirect_to(groups_path, :notice => "Group #{@group.name} was successfully updated.") }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @group.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /groups/1
  # DELETE /groups/1.xml
  def destroy
    @group = Group.find(params[:id],:conditions=>{:created_by=>current_user.id})
    @group.destroy

    respond_to do |format|
      format.html { redirect_to(groups_url) }
      format.xml  { head :ok }
    end
  end

  def current_status 
    @group = Group.find(params[:id],:conditions=>{:created_by=>current_user.id})
    @group.friends.each do |friend|
      GroupMailer.current_status(friend).deliver 
    end 
    respond_to do |format|
        format.html { redirect_to(groups_path, :notice => "Email was sent to Group #{@group.name}.") }
        format.xml  { head :ok }
    end
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    if current_user
      redirect_to :user_root
      return
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def simple_time_format(time)
    time.to_s(:simple)
  end

  def rfmark(mark='[*]') 
    "<span class=\"mfmark\">#{mark}</span>".html_safe
  end

end

app/helpers/friends_helper.rb
module FriendsHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/friends/_form.html.erb
<%= form_for(@friend) do |f| %>
  <% if @friend.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@friend.errors.count, "error") %> prohibited this friend from being saved:</h2>

      <ul>
      <% @friend.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :sex %><br />
    <%= f.radio_button(:sex, "f") %>female
    <%= f.radio_button(:sex, "m") %>male
  </div>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name, :class=>'rf_text inputbox' %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email, :class=>'rf_text inputbox' %>
  </div>
  <div class="field">
    <%= f.label :memo %><br />
    <%= f.text_area :memo, :rows=>5, :class=>'inputbox' %>
  </div>
  <div class="field">
    <%= f.label :group_id %><br />
    <%= f.collection_select(:group_id,Group.find(:all), :id, :name, :prompt=>true) %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/friends/edit.html.erb
<h2>Editing friend</h2>

<%= render 'form' %>

<%= link_to 'Show', @friend %> |
<%= link_to 'Back', groups_path %>

app/views/friends/index.html.erb
<h2>Listing friends</h2>

<table class="list">
  <tr>
    <th>Group</th>
    <th>Sex</th>
    <th>Name</th>
    <th>Email</th>
    <th>Memo</th>
    <th></th>
    <th></th>
  </tr>

<% @friends.each do |friend| %>
  <tr>
    <td><%= friend.group.name if friend.group %></td>
    <td><%= friend.sex.upcase if friend.sex %></td>
    <td><%= friend.name %></td>
    <td><%= friend.email %></td>
    <td><%= friend.memo %></td>
    <td><%= link_to 'Edit', edit_friend_path(friend) %></td>
    <td><%= link_to 'Destroy', friend, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

app/views/friends/new.html.erb
<h2>New friend</h2>

<%= render 'form' %>

<%= link_to 'Back', friends_path %>

app/views/friends/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @friend.name %>
</p>

<p>
  <b>Email:</b>
  <%= @friend.email %>
</p>

<p>
  <b>Memo:</b>
  <%= @friend.memo %>
</p>


<%= link_to 'Edit', edit_friend_path(@friend) %> |
<%= link_to 'Back', friends_path %>

app/views/groups/_form.html.erb
<%= form_for(@group) do |f| %>
  <% if @group.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@group.errors.count, "error") %> prohibited this group from being saved:</h2>

      <ul>
      <% @group.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name, :class=>'rf_text inputbox' %>
  </div>
  <div class="field">
    <%= f.label :memo %><br />
    <%= f.text_area :memo, :rows=>5, :class=>'inputbox' %>
  </div>
  <div class="field">
    <%= f.label :place %><br />
    <%= f.text_field :place, :class=>'inputbox' %>
  </div>
  <div class="field">
    <%= f.label :scheduled_at %><br />
    <%= f.datetime_select :scheduled_at, :include_blank=>true, :start_year=>Date.today.year, :order => [:year, :month, :day] %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/groups/edit.html.erb
<h2>Editing group</h2>

<%= render 'form' %>

<%= link_to 'Show', @group %> |
<%= link_to 'Back', groups_path %>

app/views/groups/index.html.erb
<h2>Groups</h2>
<div class="small">Only current 5 groups will be shown. I hope it's enough for you.</div>
<%= link_to '[+] Group', new_group_path, "class"=>"mini_button" %>
<% @groups.each do |group| %>
<div class="group_outer">
  <h3><%= group.name %></h3>
  <%= t('helpers.label.group.place') %>:
  <% if group.place && !group.place.blank? %>
    <%= group.place %><br>
  <% else %>
    (not decided yet)<br>
  <% end %>
  <%= t('helpers.label.group.scheduled_at') %>:
  <% if group.scheduled_at && !group.scheduled_at.nil? %>
    <%= simple_time_format(group.scheduled_at) %>
  <% else %>
    (not decided)
  <% end %>
  <div class="group_explanation">
  <div class="small">
    <%=simple_format(group.memo) %>
  </div>
  </div>
  <ul>
    <% group.friends.each do |friend| %> 
    <li>
    <span class="<%= friend.sex == 'm' ? "male" : "female" %>"><%= friend.name %>&nbsp;<%= friend.sex == 'm' ? "♂" : "♀" %>&nbsp;(<%= mail_to(friend.email, friend.email)  %>)</span>
    <%= link_to '[e] edit', edit_friend_path(friend), :class=>"mini_button"  %>
    <%= link_to '[d] destroy', friend, :confirm => 'Are you sure?', :method => :delete, :class=>"mini_button" %>
    </li>
    <% end %>
  </ul>
  <%= link_to '[+] member', new_friend_path("friend[group_id]"=>group.id), :class=>"mini_button" %>
  <%= link_to '[e] edit', edit_group_path(group) , :class=>"mini_button" %> 
  <%= link_to '[-] delete', group, :confirm => 'Are you sure?', :method => :delete, :class=>"mini_button" %> 
  <%= link_to '[m] mail current status', current_status_group_path(group), :confirm => 'Are you sure?', :method => :invite, :class=>"mini_button" %> 
</div>
<% end %>
<br />

app/views/groups/new.html.erb
<h2>New group</h2>

<%= render 'form' %>

<%= link_to 'Back', groups_path %>

app/views/groups/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @group.name %>
</p>

<p>
  <b>Memo:</b>
  <%= @group.memo %>
</p>
<p>
  <b>friends:</b>
	<ul>
	<% for friend in @group.friends %>
		<li><%= mail_to friend.email, friend.name %></li>
	<% end %>
	</ul>
<%= link_to 'Edit', edit_group_path(@group) %> |
<%= link_to 'Back', groups_path %>

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Ousama King - 飲み会幹事さんお助けサービス </title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>
<div id="main">
<div id="header">
<h1><%= link_to "Ousama King", root_path %> &alpha;バージョン</h1>
<div align="right">
  [<%= link_to "top", root_path %>]
<% if user_signed_in? %>
  [<%= link_to "logout", destroy_user_session_path %>]
<% end %>
</div>
</div>
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>
<%= yield %>
<div id="footer">
<span class="small">Three One Systems, Inc. All rights reserved.</span>
<br>
</div>
</div>
</body>
</html>